warning_threshold: 15
disabled_rules:
  - function_parameter_count
  - nesting
  - variable_name
  - weak_delegate
  - trailing_comma
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
line_length: 100
function_body_length: 20
file_length: 400
type_body_length:
  warning: 300
  error: 400
excluded:
  - Pods/
reporter: "xcode"